# Generated by Django 2.2.3 on 2019-07-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Board',
        ),
    ]
