# Generated by Django 2.2.3 on 2019-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190714_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='images/%Y/%m/%d'),
        ),
    ]
