# Generated by Django 2.2.3 on 2019-07-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
