# Generated by Django 2.2.3 on 2019-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUD_Blog',
            new_name='Blog',
        ),
    ]
